//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.16 at 02:09:26 PM ICT 
//

package com.discorp.staff.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.discorp.xml package.
 * <p/>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 */
@XmlRegistry
public class ObjectFactory
{
    private final static QName _TrackingNumber_QNAME = new QName(
            "http://www.dis-corp.com", "TrackingNumber");

    /**
     * Create a new ObjectFactory that can be used to create new instances of
     * schema derived classes for package: com.discorp.xml
     */
    public ObjectFactory()
    {
    }


    public StaffDetailRequest createStaffDetailRequest()
    {
        return new StaffDetailRequest();
    }

    public StaffDTOResponse createStaffDTOResponse()
    {
        return new StaffDTOResponse();
    }

    public StaffInfoDTOResponse createStaffInfoDTOResponse()
    {
        return new StaffInfoDTOResponse();
    }

    public StaffBlockRequest createStaffBlockRequest()
    {
        return new StaffBlockRequest();
    }

    public StaffDetailAddRequest createStaffDetailAddRequest()
    {
        return new StaffDetailAddRequest();
    }

    public StaffDetailAddRequest.StaffField createStaffField()
    {
        return new StaffDetailAddRequest.StaffField();
    }

    public AddStaffRequest createAddStaffRequest()
    {
        return new AddStaffRequest();
    }

    public RoleRequest createRoleRequest()
    {
        return new RoleRequest();
    }

    public StaffInformationRequest createStaffInformationRequest()
    {
        return new StaffInformationRequest();
    }

    public BlockResponse createBlockResponse()
    {
        return new BlockResponse();
    }

    public BlockRequest createBlockRequest()
    {
        return new BlockRequest();
    }

    public AddMutileRequest createAddMutileRequest()
    {
        return new AddMutileRequest();
    }

    public DeleteMutilFieldRequest createDeleteMutilFieldRequest()
    {
        return new DeleteMutilFieldRequest();
    }


    public DeleteRightRequest createDeleteRightRequest()
    {
        return new DeleteRightRequest();
    }

    public AccountResponse createAccountResponse()
    {
        return new AccountResponse();
    }

    public Account createAccount()
    {
        return new Account();
    }

    public StaffRequest createStaff()
    {
        return new StaffRequest();
    }

    public CommonStaffRequest createAccountRequest()

    {
        return new CommonStaffRequest();
    }

    public InvationCodeRequest createInvationCodeRequest()
    {
        return new InvationCodeRequest();
    }

    public InvationCodeResponse createInvationCodeResponse()
    {
        return new InvationCodeResponse();
    }

    public UpdateCreditCardRequest createUpdateCreditCardRequest()
    {
        return new UpdateCreditCardRequest();
    }

    public UpdateCreditCardResponse createUpdateCreditCardResponse()
    {
        return new UpdateCreditCardResponse();
    }

    public ChangePasswordRequest createChangePasswordRequest()
    {
        return new ChangePasswordRequest();
    }

    public ChangePasswordResponse createChangePasswordResponse()
    {
        return new ChangePasswordResponse();
    }

    public CancelServiceRequest createCancelServiceRequest()
    {
        return new CancelServiceRequest();
    }

    public CancelServiceResponse createCancelServiceResponse()
    {
        return new CancelServiceResponse();
    }

    public UpdateNotificationRequest createUpdateNotificationRequest()
    {
        return new UpdateNotificationRequest();
    }

    public UpdateNotificationResponse createUpdateNotificationResponse()
    {
        return new UpdateNotificationResponse();
    }

    public NotificationInformation createNotificationInformation()
    {
        return new NotificationInformation();
    }

    public NotificationInformationRequest createNotificationInformationRequest()
    {
        return new NotificationInformationRequest();
    }

    public NotificationInformationResponse createNotificationInformationResponse()
    {
        return new NotificationInformationResponse();
    }

    public InformationRequest createInformationRequest()
    {
        return new InformationRequest();
    }

    public InformationResponse createInformationResponse()
    {
        return new InformationResponse();
    }


    public SetupRequest createSetupRequest()
    {
        return new SetupRequest();
    }

    public SetupResponse createSetupResponse()
    {
        return new SetupResponse();
    }

    public AdminRequest createAdminRequest()
    {
        return new AdminRequest();
    }

    public CompanyResponse createCompanyResponse()
    {
        return new CompanyResponse();
    }
    public CompanyResponse.Company createCompany()
    {
        return new CompanyResponse.Company();
    }
    public CompanyResponse.BillingHistory createBillingHistory()
    {
        return new CompanyResponse.BillingHistory();
    }
    public BillingHistoryRequest createBillingHistoryRequest()
    {
        return new BillingHistoryRequest();
    }
    public CompanyResponse.AdminPayment createAdminPayment()
    {
        return new CompanyResponse.AdminPayment();
    }

    public TextEntryRequest createTextEntryRequest()
    {
        return new TextEntryRequest();
    }
    public CompanyResponse.TextEntry createTextEntry()
    {
        return  new CompanyResponse.TextEntry();
    }

    public AdminPaymentRequest createAdminPaymentRequest()
    {
        return new AdminPaymentRequest();
    }
    public EditEntryTextRequest createEditEntryTextRequest()
    {
        return new EditEntryTextRequest();
    }
    public MailServerInfoRequest createMailServerInfoRequest()
    {
        return new MailServerInfoRequest();
    }
    public MailServerInfoResponse createMailServerInfoResponse()
    {
        return new MailServerInfoResponse();
    }
    public UpdateMailServerInfoRequest createUpdateMailServerInfoRequest()
    {
        return new UpdateMailServerInfoRequest();
    }
    public UpdateMailServerInfoResponse createUpdateMailServerInfoResponse()
    {
        return new UpdateMailServerInfoResponse();
    }
    public AddCustomerRequest createAddCustomerRequest()
    {
        return new AddCustomerRequest();
    }
    public AddCustomerResponse createAddCustomerResponse()
    {
        return new AddCustomerResponse();
    }
    public CustomerRequest createCustomerRequest()
    {
        return new CustomerRequest();
    }
    public AccountRequest createAccountRequestFirstLight()
    {
        return new AccountRequest();
    }
	public ValidateVerificationCodeRequest createValidateVerificationCodeRequest()
	{
		return new ValidateVerificationCodeRequest();
	}

    public StaffReceiveSuggestionRequest createStaffReceiveSuggestionRequest()
    {
        return new StaffReceiveSuggestionRequest();
    }

	public DynamicSearchRequest createDynamicSearchRequest() {
		return new DynamicSearchRequest();
	}
	public DynamicSearchRequest.Request createRequest() {
		return new DynamicSearchRequest.Request();
	}
	public DynamicSearchResponse createDynamicSearchResponse(){
		return new DynamicSearchResponse();
	}
	public DynamicSearchResponse.CustomerInfo createCustomerInfo(){
		return new DynamicSearchResponse.CustomerInfo();
	}

    public SearchConditionRequest createSearchConditionRequest(){
        return new SearchConditionRequest();
    }
    public SearchConditionResponse createSearchConditionResponse(){
        return new SearchConditionResponse();
    }
    @XmlElementDecl(namespace = "http://www.dis-corp.com", name = "TrackingNumber")
    public JAXBElement<String> createTrackingNumber(String value)
    {
        return new JAXBElement<String>(_TrackingNumber_QNAME, String.class,
                null, value);
    }
}
